### ISSUE TITLE
Getting: WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that! container

### ISSUE THREAD

**Issue by visionarchitect** [CERT-Polska/Artemis#363] opened 2023-06-07 09:24 UTC
When building using "quick steps" (docker compose)
I am getting: WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that! container  
Solved by changing image to 4.4.6 version

**Comment by kazet** [comment] 2023-06-07 10:51
duplicate of #264  - there is a PR that will document that as well (https://github.com/CERT-Polska/Artemis/pull/315)

**Closed by kazet** 2023-06-07 10:51 UTC
